CREATE TABLE FIU(
    ID VARCHAR PRIMARY KEY NOT NULL,
    NAME VARCHAR NOT NULL
);

CREATE TYPE FUNCTION_STATE AS ENUM('PENDING', 'ACTIVE', 'INACTIVE', 'FAILED');

CREATE TABLE FUNCTIONS(
   ID VARCHAR PRIMARY KEY NOT NULL,
   FIU_ID VARCHAR NOT NULL,
   FUNCTION_NAME VARCHAR NOT NULL,
   STATE FUNCTION_STATE DEFAULT 'PENDING',
   S3_LOCATION VARCHAR NOT NULL,
   RESULT_JSON_SCHEMA VARCHAR NOT NULL,
   CREATED TIMESTAMP DEFAULT NOW(),
   LAST_UPDATED TIMESTAMP DEFAULT NOW()
);

CREATE TYPE JOB_STATE AS ENUM('CREATED', 'PROCESSING', 'FAILED', 'SUCCESS');

CREATE TABLE JOBS(
   ID VARCHAR PRIMARY KEY NOT NULL,
   FUNCTION_ID VARCHAR NOT NULL,
   FIU_ID VARCHAR NOT NULL,
   STATE JOB_STATE DEFAULT 'CREATED',
   RETRY_COUNT INT DEFAULT 0,
   AA_ID VARCHAR NOT NULL,
   REQUEST_PARAMS VARCHAR NOT NULL,
   RESULT VARCHAR,
   CREATED TIMESTAMP DEFAULT NOW(),
   LAST_UPDATED TIMESTAMP DEFAULT NOW()
);
