version: '3.7'

services:

  postgres:
    container_name: "virtual-room"
    image: postgres
    volumes:
      - virtual-room:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  virtual-room:
    driver: local